extern.h: fix weird clang warning about incompatible types
This warning literally makes no sense, and the fix is even more bizarre,
But it's Apple's clang, so it's probably just a broken compiler:

	zap.c:3695:9: warning: promoted type 'int' of K&R function parameter is not compatible with the parameter type 'boolean'
		  (aka 'signed char') declared in a previous prototype
	boolean moncast;
	        ^
	In file included from zap.c:5:
	In file included from ../include/hack.h:121:
	../include/extern.h:2460:7: note: previous declaration is here
	E int FDECL(zap_over_floor, (XCHAR_P,XCHAR_P,int,boolean *,boolean));
	      ^
	../include/extern.h:2460:67: note: instantiated from:
	E int FDECL(zap_over_floor, (XCHAR_P,XCHAR_P,int,boolean *,boolean));
	                                                           ^
	1 warning generated.

Signed-off-by: Steven Noonan <steven@uplinklabs.net>